version: '3.9'


services:
  app:
    build: 
    command: npm start
    ports:
      - '5000:5000'
    volumes:
        - .:/usr/app

db:
  database:
    image: postgres:13
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=houserent"
    ports:
      - 5433:5432
    volumes:
      - data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm

